var TIME_RANGE = 15;
var SIZE_RANGE = 2;

var _findGroups = function(name, time, size, timeRange, sizeRange) {
  if (!timeRange && !sizeRange) {
    return Groups.find({restaurant: name, time: time, size: size}).fetch();
  } else if (!timeRange && sizeRange) {
    return Groups.find({$and : [
      {restaurant: name, time: time},
      {size: {$gte: size - SIZE_RANGE, $lte: size + SIZE_RANGE}}
      ]
    }).fetch();
  } else if (timeRange && !sizeRange) {
    // this never happens
    return Groups.find({ $and : [
      {restaurant: name, size: size},
      {time: {$gte: time - TIME_RANGE, $lte: time + TIME_RANGE}}
      ]
    }).fetch();   
  } else {
    return Groups.find({ $and : [
      {restaurant: name},
      {time: {$gte: time - TIME_RANGE, $lte: time + TIME_RANGE}},
      {size: {$gte: size - SIZE_RANGE, $lte: size + SIZE_RANGE}}
      ]
    }).fetch();
  }
};

Meteor.methods({
  getLocalRestaurants: function(loc) {
    var auth = Accounts.loginServiceConfiguration.findOne({service: 'yelp'});

    var yelp = Meteor.npmRequire("yelp").createClient({
      consumer_key: auth.consumerKey, 
      consumer_secret: auth.consumerSecret,
      token: auth.accessToken,
      token_secret: auth.accessTokenSecret,
    });

    var ll = loc.latitude + "," + loc.longitude;

    var a_search = Async.wrap(yelp, "search");

    var res = a_search({term: "food", ll: ll, limit: 5});
    return res;
  },

  createGM: function(name, people) {
    var GMAPI = Meteor.npmRequire("groupme").Stateless;
    var auth = Accounts.loginServiceConfiguration.findOne({service: "groupme"});
    var a_create = Async.wrap(GMAPI.Groups, "create");

    var res = a_create(auth.key, {name: name, description: "autogenerated GroupMe for FoodMe", share: true});
    return res.share_url;
  },

  findGroups: function(name, time, size, timeRange, sizeRange) {
    var out = _findGroups(name, time, size, timeRange, sizeRange);
    return out;
  },

  groupAdd: function(person, restaurant, sTime, sSize) {

    var groups, retCode = 0;
    var time = parseInt(sTime, 10);
    var size = parseInt(sSize, 10);

    groups = _findGroups(restaurant, time, size, false, false);
    // TODO - add Meteor.userId() to the group^ here
    
    if (groups.length == 0) {
      console.log("couldn't find any groups which matched exactlyish");
      retCode = 1;
      groups = _findGroups(restaurant, time, size, false, true);
    } else {
      console.log("found a group which matched exactly", groups);
      var group_id = groups[0]._id;
      Groups.update({_id: group_id}, {$addToSet: {people: person}});
      if (Groups.findOne(group_id).people.length == Groups.findOne(group_id).size) {
        Groups.update({_id: group_id}, {$set: {atCapacity: true}});
      }
      return {id: group_id, retCode: retCode}; 
    }

    if (groups.length == 0) {
      console.log("couldn't find any groups with size in the range")
      retCode = 2;
      groups = _findGroups(restaurant, time, size, true, true);
    }

    if (groups.length == 0) {
      console.log("couldn't find any groups with time or size in range, inserting");
      retCode = 3;

      var id = Groups.insert({
        restaurant: restaurant,
        time: time,
        size: size,
        people: [person],
        atCapacity: false
      });
      return {id: id, retCode: retCode};
    }

    var group_id = groups[0]._id;
    var out = {id: group_id, retCode: retCode};
    return out;
  }
})
